version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Process PR data
          command: ./ci-scripts/process-pr-data.sh

workflows:
  cd_pr_preview:
    jobs:
      - deploy:
          context:
            - aws-credentials
          filters:
            branches:
              ignore:
                - main
