version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

commands:
  get-pr-subdomain:
    parameters:
      pr-subdomain:
        type: string
        default: ".pr.appstag.my-own-aws-tests.com"
      pr-url-path:
        type: string
        default: https://github.com/antoniovizuete/poc-preview-pr-front/pull/
    steps:
      - run: |
          PR_URL_PATH="<< parameters.pr-url-path >>"
          PR_NUMBER=${CIRCLE_PULL_REQUEST//$PR_URL_PATH/}
          SUBDOMAIN="pr-$PR_NUMBER<< parameters.pr-subdomain >>"

          echo "export PR_SUBDOMAIN=$SUBDOMAIN" >> $BASH_ENV
  deploy-to-s3-folder:
    parameters:
      s3-bucket-name:
        type: string
    steps:
      - get-pr-subdomain
      - run:
          name: Deploy to S3
          command: |
            S3_PATH="s3://<< parameters.s3-bucket-name >>/$PR_SUBDOMAIN/index.html"
            aws s3 cp ./index.html $S3_PATH

      - run:
          name: Please inspect this step to show the PR Preview URL
          command: |
            echo "https://$PR_SUBDOMAIN"

jobs:
  deploy:
    executor: aws-cli/default
    parameters:
      s3-bucket-name:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - deploy-to-s3-folder:
          s3-bucket-name: << parameters.s3-bucket-name >>

workflows:
  cd_pr_preview:
    jobs:
      - deploy:
          #s3-bucket-name: $S3_BUCKET_NAME
          s3-bucket-name: "my-own-test-bucket-1q6acvbs"
          context:
            - aws-credentials
          filters:
            branches:
              ignore:
                - main
