version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - run: aws sts get-caller-identity
      - run: echo $CIRCLE_PULL_REQUESTS
      - run: echo $CIRCLE_REPOSITORY_URL

workflows:
  cd_pr_preview:
    jobs:
      - deploy:
          context:
            - aws-credentials
          filters:
            branches:
              ignore:
                - main
